# Generated by Django 6.0.4 on 2026-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitycategory_alter_activitytype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='activity_videos/', verbose_name='Видео тренировки'),
        ),
    ]
