# Generated by Django 6.0.4 on 2026-04-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание упражнения'),
        ),
    ]
