# Generated by Django 6.0.4 on 2026-04-23 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='votes_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='votes_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecordVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_votes', to='activities.useractivitylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'log')},
            },
        ),
    ]
