# Generated by Django 6.0.4 on 2026-04-27 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_useractivitylog_is_verified_useractivitylog_votes_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivalry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_rivals', to=settings.AUTH_USER_MODEL)),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by_athletes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('athlete', 'rival')},
            },
        ),
    ]
