# Generated by Django 6.0.4 on 2026-04-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_rivalry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.useractivitylog'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('comment', 'Комментарий'), ('rival', 'Соперник')], max_length=10),
        ),
    ]
